# Generated by Django 5.0.4 on 2024-05-06 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("type_award", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("photo", models.TextField()),
                ("flag", models.TextField()),
                ("country", models.CharField(max_length=100)),
                ("points", models.IntegerField()),
                ("rating", models.FloatField()),
                ("best_position", models.IntegerField()),
                ("current_position", models.IntegerField()),
                ("start_date_best_position", models.DateField()),
                ("end_date_best_position", models.DateField()),
                ("points_year", models.IntegerField()),
                ("points_semester", models.IntegerField()),
                (
                    "awards",
                    models.ManyToManyField(
                        blank=True, related_name="musicians", to="musicapp.award"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.IntegerField()),
                ("position", models.IntegerField()),
                (
                    "musician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicapp.musician",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=50)),
                ("points", models.IntegerField()),
                (
                    "musician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicapp.musician",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gem", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("week", models.IntegerField(default=0)),
                ("release_year", models.PositiveSmallIntegerField()),
                ("genre", models.CharField(max_length=100)),
                ("album", models.TextField()),
                ("youtube", models.TextField()),
                (
                    "musicians",
                    models.ManyToManyField(
                        related_name="songs", to="musicapp.musician"
                    ),
                ),
            ],
        ),
    ]
