# Generated by Django 5.0.4 on 2024-05-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicapp", "0002_alter_musician_best_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="award",
            name="type_award",
            field=models.IntegerField(default=0),
        ),
    ]
