# Generated by Django 5.0.4 on 2024-05-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicapp", "0003_award_points_alter_award_type_award"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musician",
            name="current_position",
            field=models.IntegerField(default=99999),
        ),
    ]
