# Generated by Django 5.0.4 on 2024-05-18 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicapp", "0004_alter_musician_current_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="ranking",
            name="profile",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
