# Generated by Django 5.0.4 on 2024-05-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicapp", "0005_ranking_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="year",
            field=models.IntegerField(default=0),
        ),
    ]
